<div id="searchBox">
	<div id="sideSearch">
	<form action="" method="get">
		<ul id="sideSport"><p>シューズ</p>
			<li>ライフスタイル (139)</li>
			<li>ランニング (55)</li>
			<li>バスケットボール (48)</li>
			<li>サッカー／フットボール (63)</li>
			<li>トレーニング (10)</li>
			<li>ベースボール&ソフトボール (4)</li>
			<li>ゴルフ (14)</li>
			<li>スケートボード (45)</li>
			<li>テニス (15)</li>
			<li>陸上競技 (13)</li>
		</ul>
		<ul id="sideChar">特長
			<li><label><input type="checkbox">レース</label></li>
			<li><label><input type="checkbox">素足のような履き心地</label></li>
			<li><label><input type="checkbox">クッショニング</label></li>
			<li><label><input type="checkbox">安定性</label></li>
		</ul>重さ
		<ul id="sideItem">
			<li><label><input type="checkbox" name="weight[]" value="1">特に軽い</label></li>
			<li><label><input type="checkbox" name="weight[]" value="2">重い</label></li>
			<li><label><input type="checkbox" name="weight[]" value="3">普通</label></li>
			<li><label><input type="checkbox" name="weight[]" value="4">重い</label></li>
			<li><label><input type="checkbox" name="weight[]" value="5">特に重い</label></li>
		</ul>
		<ul id="sideWide">幅
			<li><label><input type="checkbox" name="width[]" value="1">特に狭い</label></li>
			<li><label><input type="checkbox" name="width[]" value="2">狭い</label></li>
			<li><label><input type="checkbox" name="width[]" value="3">普通</label></li>
			<li><label><input type="checkbox" name="width[]" value="4">広い</label></li>
			<li><label><input type="checkbox" name="width[]" value="5">特に広い</label></li>
		</ul>
		カラー
		<ul id="sideColor">
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>
			<a href=""></a>

		</ul>
		サイズ
		<ul id="sideSize">
			<li>22.5</li>
			<li>23</li>
			<li>23.5</li>
			<li>24</li>
			<li>24.5</li>
			<li>25</li>
			<li>25.5</li>
			<li>26</li>
			<li>26.5</li>
			<li>27</li>
			<li>27.5</li>
			<li>28</li>
			<li>28.5</li>
			<li>29</li>
			<li>29.5</li>
			<li>30</li>
			<li>30.5</li>
			<li>31</li>
			<li>32</li>
			<li>33</li>
		</ul>
		<input type="submit" value="送信">
		<a href="http://localhost/ecSite/Page/itemView.php">リセット</a>
	</div><!--sideSearch-->
</form>
	<div id="searchMain">
		<h1>検索結果</h1>
		<div id="searchItem">
		<?php foreach ($this->itemList as $row) : ?>
			<div class="item searchResult">
				<a href="itemPage.php?itemNo=<?= $row['itemNo']?>&color=<?=$row['colorNo']?>">
					<img src="img/Item/<?= $row['ItemIMGName']?>">
					<p><?= $row['itemName']?></p>
					<p class="item-cate"><?= $row['ItemSex'] == 1 ? "メンズ" : 'レディース'?></p>
					<p class="value"></p>
					<div class="rankStar"></div>
				</a><!-- rankItem -->
			</div><!-- athorItem -->
			<?php endforeach;?>
		</div>
	</div><!--searchMain-->
</div><!-- searchBox閉じ -->